### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefinedPlease report this to https://git...

### ISSUE THREAD

**Issue by sunny-rajkotiya** [sgengler/atom-trello#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: [atom-trello](https://github.com/sgengler/atom-trello) package, v0.3.0
### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined
Please report this to https://github.com/chjj/marked.

```
At /home/knolly/.atom/packages/atom-trello/node_modules/marked/lib/marked.js:1226

TypeError: Cannot read property 'replace' of undefined
Please report this to https://github.com/chjj/marked.
    at Lexer.lex (/home/knolly/.atom/packages/atom-trello/node_modules/marked/lib/marked.js:138:5)
    at Function.Lexer.lex (/home/knolly/.atom/packages/atom-trello/node_modules/marked/lib/marked.js:129:16)
    at marked (/home/knolly/.atom/packages/atom-trello/node_modules/marked/lib/marked.js:1218:31)
    at AtomTrelloView.module.exports.AtomTrelloView.cardsView (/home/knolly/.atom/packages/atom-trello/lib/atom-trello-view.coffee:64:17)
    at AtomTrelloView.module.exports.AtomTrelloView.viewForItem (/home/knolly/.atom/packages/atom-trello/lib/atom-trello-view.coffee:45:26)
    at AtomTrelloView.module.exports.SelectListView.populateList (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:206:29)
    at AtomTrelloView.module.exports.SelectListView.setItems (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:167:12)
    at AtomTrelloView.module.exports.AtomTrelloView.showView (/home/knolly/.atom/packages/atom-trello/lib/atom-trello-view.coffee:75:6)
    at /home/knolly/.atom/packages/atom-trello/lib/atom-trello-view.coffee:132:8
    at Request._callback (/home/knolly/.atom/packages/atom-trello/node_modules/node-trello/lib/node-trello.js:94:5)
    at Request.self.callback (/home/knolly/.atom/packages/atom-trello/node_modules/node-trello/node_modules/request/request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/knolly/.atom/packages/atom-trello/node_modules/node-trello/node_modules/request/request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/knolly/.atom/packages/atom-trello/node_modules/node-trello/node_modules/request/request.js:1266:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```
### Commands

```
     -0:53.4.0 emmet:split-join-tag (atom-pane.pane.active)
     -0:51.8.0 command-palette:toggle (atom-pane.pane.active)
  9x -0:46.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:40.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:39.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:39.5.0 atom-terminal:open-project-root (atom-pane.pane.active)
  3x -0:30.7.0 emmet:split-join-tag (atom-pane.pane.active)
     -0:21.2.0 atom-terminal:open (ul.list-inline.tab-bar.inset-panel)
     -0:12.2.0 atom-trello:toggle (ul.list-inline.tab-bar.inset-panel)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true
  },
  "atom-trello": {
    "devKey": "32e780a699cbfe2f49cf2f92bea17c57",
    "token": "ac3833fa31137857e5571a36f5242cadfb5a45cfb4e674b83b985ff3299a53dc"
  }
}
```
### Installed Packages

``` coffee
# User
atom-terminal, v0.8.0
atom-trello, v0.3.0
build, v0.49.2
coffee-compile, v0.19.2
coffee-navigator, v0.0.16
color-picker, v2.0.12
emmet, v2.3.15
language-vue-component, v0.3.0
minimap, v4.16.2
preview-plus, v1.2.6
project-manager, v2.6.5
terminal-plus, v0.4.2

# Dev
No dev packages
```

**Comment by sgengler** [comment]
I believe this is an issue with the markdown processor being passed nothing. I updated to only try to process the description markdown if a description exists. This is fixed here as part of a recent update to allow toggling of descriptions: 69d3b6670c976cf5bf49e1b5fd53179895bfbed5
